/* eslint-disable import/no-anonymous-default-export */
import { FaTwitter, FaSearch, FaPen, FaCheck, FaSortAmountUp, FaToggleOn, FaToggleOff } from 'react-icons/fa';
import {
  RiArrowRightSLine,
  RiArrowLeftSLine,
  RiShareForwardLine,
  RiPriceTag3Line,
  RiLinksLine,
  RiStarLine,
  RiAddLine,
  RiArrowDownSLine,
  RiCloseLine,
  RiDatabase2Line,
  RiMore2Fill,
  RiFilter3Line,
  RiGooglePlayLine,
  RiAppStoreLine,
  RiLoader4Line,
  RiInboxArchiveLine,
  RiDeleteBin7Line,
  RiSettings4Line,
  RiSearch2Line,
  RiEditLine,
  RiPlantLine,
  RiInboxLine,
  RiTaskLine,
  RiFilePaperLine,
  RiTerminalLine,
  RiShieldFlashLine,
  RiBankCardLine,
  RiBookOpenLine,
  RiFootballLine,
  RiHome2Line,
  RiQuillPenLine,
  RiCheckDoubleLine,
  RiUserLine,
  RiDeleteBin4Line,
  RiChat3Line,
  RiNotification3Line,
  RiSoundModuleLine,
  RiUploadCloud2Line,
  RiArrowGoBackFill,
  RiInformationLine,
  RiLockLine,
  RiCheckFill,
  RiStarFill,
  RiDownloadCloud2Line,
  RiCheckboxCircleLine,
  RiMenu2Line,
  RiTeamLine,
  RiSaveLine,
  RiTimeLine,
  RiArrowRightUpLine,
  RiPencilLine,
  RiArrowUpSLine,
  RiFolder2Line,
  RiAddFill,
  RiSendPlaneFill,
  RiCompass3Line,
  RiSettings3Line,
  RiFileCopyLine,
  RiMoreFill,
  RiAtLine,
  RiHashtag,
  RiQuestionLine,
  RiSignalWifiErrorLine,
  RiFlagLine,
  RiErrorWarningLine,
  RiSunCloudyLine,
  RiMoonClearLine,
  RiEyeLine,
  RiEyeOffLine,
  RiMicLine,
  RiMailUnreadLine,
  RiMailSendLine,
  RiShieldKeyholeLine,
} from 'react-icons/ri';
import { TiWarning } from 'react-icons/ti';
import { IconType as RiIconType } from 'react-icons/lib';

export default {
  Twitter: FaTwitter,
  Search: FaSearch,
  ArrowRight: RiArrowRightSLine,
  ArrowLeft: RiArrowLeftSLine,
  ArrowUp: RiArrowUpSLine,
  Pen: FaPen,
  Warning: TiWarning,
  Plus: RiAddFill,
  FaCheck,
  Share: RiShareForwardLine,
  Tag: RiPriceTag3Line,
  Link: RiLinksLine,
  Star: RiStarLine,
  Add: RiAddLine,
  ArrowDown: RiArrowDownSLine,
  Close: RiCloseLine,
  DatabaseLine: RiDatabase2Line,
  KebabMenu: RiMore2Fill,
  Filter: RiFilter3Line,
  SortUp: FaSortAmountUp,
  AppStore: RiAppStoreLine,
  PlayStore: RiGooglePlayLine,
  Loader: RiLoader4Line,
  ToggleOn: FaToggleOn,
  ToggleOff: FaToggleOff,
  Archive: RiInboxArchiveLine,
  Delete: RiDeleteBin7Line,
  Settings: RiSettings4Line,
  SearchLine2: RiSearch2Line,
  Edit: RiEditLine,
  Insight: RiPlantLine,
  Feedback: RiInboxLine,
  Task: RiTaskLine,
  Reports: RiFilePaperLine,
  Terminal: RiTerminalLine,
  FlashShield: RiShieldFlashLine,
  Billing: RiBankCardLine,
  Docs: RiBookOpenLine,
  QuickHelp: RiFootballLine, // To be changed
  Home: RiHome2Line,
  QuillPen: RiQuillPenLine,
  CheckDoubleLine: RiCheckDoubleLine,
  User: RiUserLine,
  DeleteBin4: RiDeleteBin4Line,
  Chat: RiChat3Line,
  Notification: RiNotification3Line,
  Info: RiInformationLine,
  SearchOption: RiSoundModuleLine,
  Upload: RiUploadCloud2Line,
  GoBack: RiArrowGoBackFill,
  Lock: RiLockLine,
  Check: RiCheckFill,
  StarFill: RiStarFill,
  Download: RiDownloadCloud2Line,
  CirclerCheck: RiCheckboxCircleLine,
  Menu: RiMenu2Line,
  Team: RiTeamLine,
  Save: RiSaveLine,
  Time: RiTimeLine,
  ArrowRightUp: RiArrowRightUpLine,
  Pencil: RiPencilLine,
  Folder: RiFolder2Line,
  Send: RiSendPlaneFill,
  Discovery: RiCompass3Line,
  Configure: RiSettings3Line,
  Copy: RiFileCopyLine,
  MoreLine: RiMoreFill,
  At: RiAtLine,
  Hashtag: RiHashtag,
  QuestionLine: RiQuestionLine,
  Error: RiSignalWifiErrorLine,
  FlagWarning: RiFlagLine,
  RoundWarning: RiErrorWarningLine,
  Sun: RiSunCloudyLine,
  Moon: RiMoonClearLine,
  Eye: RiEyeLine,
  EyeOff: RiEyeOffLine,
  Mic: RiMicLine,
  MailUnread: RiMailUnreadLine,
  MailSend: RiMailSendLine,
  ShieldKeyhole: RiShieldKeyholeLine,
};

export {
  RiComputerLine as Computer,
  RiInboxArchiveLine as Inbox,
  RiHashtag as HashTag,
  RiUserAddLine as UserAdd,
  RiLifebuoyLine as Lifebuoy,
} from 'react-icons/ri';

export type IconType = RiIconType;
